Added a workflow for automatic release uploads
ufrshubham/sfml-project-template pull request #3
Opened 2024-11-13 19:14 UTC by MockJoke

- Updated github workflow to trigger build checks on version tag push and to automatically upload builds as releases on manual trigger from publish releases
- Updated CMakeLists.txt to collect source and header files from subfolders as well
- Updated CMakeLists.txt to copy resources folder to binary output directory to handle resource dependency for the executable
- Updated README.md (fixed some typos)

2024-11-15 02:36 UTC, ufrshubham commented on .github/workflows/build-release.yml
> +      release:
Just a minor formatting suggestion
```suggestion
  release:
```

2024-11-15 02:38 UTC, ufrshubham requested changes
LGTM! Thanks for the PR. I've just added a minor suggestion🙂

2024-11-15 12:02 UTC, MockJoke commented
Fixed it.

2024-11-16 05:27 UTC, ufrshubham approved these changes

2024-11-16 05:30 UTC, ufrshubham commented
@MockJoke is it possible for you to also update the readme with steps on how to publish a release?

2024-11-16 11:07 UTC, merged